service: myProject

plugins:
  - serverless-esbuild
  - serverless-offline

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: 'test'
  apiGateway:
    restApiId: !Ref ApiGateway
    restApiRootResourceId: !GetAtt ApiGateway.RootResourceId
  iamRoleStatements:
    - Effect: Allow # / Deny
      Action:
        - s3:*
        - dynamodb:*
        - cognito-idp:*
        - cognito-identity:*
        - cloudsearch:*
        - ssm:GetParameter
        - cognito-idp:AdminCreateUser
      Resource:
        - '*'
  vpc: //from here
    securityGroupIds:
      - !Ref LambdaSecurityGroup
    subnetIds:
      - !Ref SubnetA
      - !Ref SubnetB
  environment:
    DB_NAME: ${self:custom.DB_NAME}
    DB_USER: ${self:custom.DB_USERNAME}
    DB_PASS: ${self:custom.DB_PASSWORD}
    DB_PORT: ${self:custom.DB_PORT}
    DB_HOST: ${self:custom.PROXY_ENDPOINT}

custom:
  userPoolName: test-user-pool-${sls:stage}
  userPoolClientName: test-user-pool-client-${sls:stage}
  esbuild:
    minify: true
  developerStage: ${env:DEVELOPER_IDENTIFIER,'test'}
  //from here
  DB_NAME: db_${self:provider.stage}
  DB_USERNAME: postgres
  DB_PASSWORD: nare12345
  DB_PORT: !GetAtt RDSInstance.Endpoint.Port
  PROXY_ENDPOINT: !GetAtt RDSProxy.Endpoint
  PROXY_NAME: db-proxy-${self:provider.stage}
  VPC_CIDR: 10


resources:
  Resources:
      ApiGateway:
        Type: AWS::ApiGateway::RestApi
        Properties:
          Name: 'test-api'

functions:
  getOfferings:
    handler: index.handler
    events:
      - http:
          path: /offerings
          method: get
          cors:
            origin: '*'
            headers:
              - '*'
  offeringsPremium:
    handler: offeringFunctions/premium.offering
    events:
      - http:
          path: /offeringsPremium/{id}
          method: get
          cors:
            origin: '*'
            headers:
              - '*'
  filterCategories:
    handler: offeringFunctions/filter.filterCategories
    events:
      - http:
          path: /filterCategories/
          method: get
          cors:
            origin: '*'
            headers:
              - '*'
  matchCategories:
    handler: offeringFunctions/matchCategories.match
    events:
      - http:
          path: /matchCategories/
          method: post
          cors:
            origin: '*'
            headers:
              - '*'

