
export const offerings : {
    unique_id:number,
    offering_name : string,
    asset_class_id: number,
    // asset_class_name:string,
    structure_name: string,
    sector_name: string,
    state_abbreviation: string,
    target_irr: string,
    offering_profile_image: null,
    minimum_investment: number,
    } [] =
    [
        {
        "unique_id":1,
        "offering_name": "15191 Sylmar QOF",
        "asset_class_id": 1,
        //"asset_class_name": "Real Estate",
        "structure_name": "Qualified Opportunity Fund",
        "sector_name": "Multifamily",
        "state_abbreviation": "CA,NC,AZ",
        "target_irr": "15.4%",
        "offering_profile_image": null,
        "minimum_investment": 250000
    },
    {
        "unique_id":2,
        "offering_name": "33 Tax Advantaged Opportunity Zone Fund",
        "asset_class_id": 1,
        //"asset_class_name": "Real Estate",
        "structure_name": "Qualified Opportunity Fund",
        "sector_name": "Office",
        "state_abbreviation": "CA,NC,AZ",
        "target_irr": "12%",
        "minimum_investment": 10000,
        "offering_profile_image": null,
    },
    {
        "unique_id":3,
        "offering_name": "3LB Equities Opportunity Zone Fund",
        "asset_class_id": 1,
        //"asset_class_name": "Real Estate",
        "structure_name": "Qualified Opportunity Fund",
        "sector_name": "Retail",
        "state_abbreviation": "CA,NC,AZ",
        "target_irr": "25%+",
        "minimum_investment": null,
        "offering_profile_image": null,
    },
    {
        "unique_id":4,
        "offering_name": "620 Hudson House LLC",
        "asset_class_id": 1,
        //"asset_class_name": "Real Estate",
        "structure_name": "Qualified Opportunity Fund",
        "sector_name": "Industrial",
        "state_abbreviation": "CA,NC,AZ",
        "target_irr": null,
        "minimum_investment": 500000,
        "offering_profile_image": null,
    },
    {
        "unique_id":5,
        "offering_name": "828 Studios OZ Fund",
        "asset_class_id": 2,
        //"asset_class_name": "Operating Business",
        "structure_name": "Qualified Opportunity Fund",
        "sector_name": "Mixed Use",
        "state_abbreviation": "CA,NC,AZ",
        "target_irr": "16.9%",
        "minimum_investment": 250000,
        "offering_profile_image": null,
    },
    {
        "unique_id":6,
        "offering_name": "15192 Sylmar QOF",
        "asset_class_id": 1,
        //"asset_class_name": "Real Estate",
        "structure_name": "Qualified Opportunity Fund",
        "sector_name": "Multifamily",
        "state_abbreviation": "CA,NC,AZ",
        "target_irr": "15.4%",
        "minimum_investment": 250000,
        "offering_profile_image": null,
    },
    {
        "unique_id":7,
        "offering_name": "15193 Sylmar QOF",
        "asset_class_id": 1,
        //"asset_class_name": "Real Estate",
        "structure_name": "Qualified Opportunity Fund",
        "sector_name": "Multifamily",
        "state_abbreviation": "CA,NC,AZ",
        "target_irr": "15.4%",
        "minimum_investment": 250000,
        "offering_profile_image": null,
    }
]

export const offeringsPremium: {
    unique_id:number,
    sponsor_name:string,
    offering_name : string,
    structure_name:string,
    asset_class_id:number,
    offering_description:string,
    offering_webpage:string,
    sector_name:string,
    strategy_name:string,
    state_abbreviation:string,
    portfolio_type_name:string,
    investor_requirement_name:string,
    fundraising_status_name:string,
    target_irr:string,
    target_equity_multiple:string|number,
    target_cash_on_cash:string|number
    minimum_investment:number,
    estimated_hold_period:string,
    estimated_first_distribution:string|number,
    offering_webinar:string|number
    offering_deck:string|number,
    offering_image_1:string,
    offering_image_2:string,
    offering_image_3:string,
    offering_image_4:string,
    offering_image_5:string,
    sponsor_logo:string,
    sponsor_contact_name:string,
    sponsor_contact_title:string,
    sponsor_contact_email:string,
    sponsor_contact_phone:string|number,
    sponsor_description:string,
    sponsor_leadership_1_image:string,
    sponsor_leadership_1_name:string,
    sponsor_leadership_1_title:string,
    sponsor_leadership_1_linkedin:string,
    sponsor_leadership_2_image:string,
    sponsor_leadership_2_name:string,
    sponsor_leadership_2_title:string,
    sponsor_leadership_2_linkedin:string,
    sponsor_video:string,
    profile_image:string,
}[]=[
    {
        "unique_id":1,
        "sponsor_name":"Xebec Realty",
        "offering_name": "15191 Sylmar QOF",
        "structure_name":"Qualified Opportunity Fund",
        "asset_class_id":1,
        "offering_description":"Sylmar QOF, LLC is a Qualified Opportunity Zone Fund investment opportunity for the ground-up development of a dedicated sound stage facility located in Sylmar, CA. The site was acquired by Xebec in June of 2020 to develop a 120,401 square foot building, with an approximately $47.8 million project cost and which is pre-leased to an operator of sound stage studios under a 10-year lease.Situated on a 3.7-acre site designated as an opportunity zone for U.S. income tax purposes, the property is located in Sylmar, California, in the highly desirable East San Fernando Valley industrial submarket of Los Angeles and is also located within the Thirty-Mile Zone, or TMZ, an important factor in attracting studio, film, and media users in the Southern California market.",
        "offering_webpage":"https://xebecrealty.com/",
        "sector_name":'Multifamily',
        "strategy_name":"null",
        "state_abbreviation":"CA,NC,AZ",
        "portfolio_type_name":"Single Asset",
        "investor_requirement_name":"Accredited Only",
        "fundraising_status_name":"Open",
        "target_irr":"15.4%",
        "target_equity_multiple":null,
        "target_cash_on_cash":"null",
        "minimum_investment":250000,
        "estimated_hold_period":"10 years",
        "estimated_first_distribution":"null",
        "offering_webinar":"string|number",
        "offering_deck":"string|number",
        "offering_image_1":"string",
        "offering_image_2":"string",
        "offering_image_3":"string",
        "offering_image_4":"string",
        "offering_image_5": null,
        "sponsor_logo":null,
        "sponsor_contact_name":null,
        "sponsor_contact_title":null,
        "sponsor_contact_email":null,
        "sponsor_contact_phone":null,
        "sponsor_description":null,
        "sponsor_leadership_1_image":null,
        "sponsor_leadership_1_name":null,
        "sponsor_leadership_1_title":null,
        "sponsor_leadership_1_linkedin":null,
        "sponsor_leadership_2_image":null,
        "sponsor_leadership_2_name":null,
        "sponsor_leadership_2_title":null,
        "sponsor_leadership_2_linkedin":null,
        "sponsor_video":null,
        "profile_image":null
},
    {
        "unique_id":2,
        "sponsor_name": "33 OZ Capital Management LLC",
        "offering_name": "33 Tax Advantaged Opportunity Zone Fund",
        "structure_name": "Qualified Opportunity Fund",
        "asset_class_id": 1,
        "offering_description": "Affordable housing, multifamily housing, workforce housing, industrial, and commercial real estate primarily in Atlanta and surrounding cities.",
        "offering_webpage": "https://www.33holdings.com/invest/",
        "sector_name": "Office",
        "strategy_name": "Ground Up Construction",
        "state_abbreviation":  "CA,NC,AZ",
        "portfolio_type_name": "Multi Asset",
        "investor_requirement_name": "Accredited Only",
        "fundraising_status_name": "Open",
        "target_irr": "12%",
        "target_equity_multiple": null,
        "target_cash_on_cash": null,
        "minimum_investment": 10000,
        "estimated_hold_period": "10+ years",
        "estimated_first_distribution": null,
        "offering_webinar": null,
        "offering_deck": null,
        "offering_image_1": "https://www.33holdings.com/wp-content/uploads/2022/01/ATL_Day.jpg",
        "offering_image_2": null,
        "offering_image_3": null,
        "offering_image_4": null,
        "offering_image_5": null,
        "sponsor_logo":null,
        "sponsor_contact_name":null,
        "sponsor_contact_title":null,
        "sponsor_contact_email":null,
        "sponsor_contact_phone":null,
        "sponsor_description":null,
        "sponsor_leadership_1_image":null,
        "sponsor_leadership_1_name":null,
        "sponsor_leadership_1_title":null,
        "sponsor_leadership_1_linkedin":null,
        "sponsor_leadership_2_image":null,
        "sponsor_leadership_2_name":null,
        "sponsor_leadership_2_title":null,
        "sponsor_leadership_2_linkedin":null,
        "sponsor_video":null,
        "profile_image":null
    },
    {
        "unique_id":3,
        "sponsor_name": "3LB Equities",
        "offering_name": "3LB Equities Opportunity Zone Fund",
        "structure_name": "Qualified Opportunity Fund",
        "asset_class_id": 1,
        "offering_description": "3LB is presently seeking multi-family assets located in Texas Opportunity Zones or land that could be used in the development of multi-family properties located in Texas Opportunity Zones.",
        "offering_webpage": "https://3lbequities.com/opportunity-fund",
        "sector_name": "Office",
        "strategy_name": "Ground Up Construction",
        "state_abbreviation":  "CA,NC,AZ",
        "portfolio_type_name": "Multi Asset",
        "investor_requirement_name": "Accredited Only",
        "fundraising_status_name": "Open",
        "target_irr": "25%+",
        "target_equity_multiple": null,
        "target_cash_on_cash": null,
        "minimum_investment": null,
        "estimated_hold_period": "10+ years",
        "estimated_first_distribution": null,
        "offering_webinar": "10+ years",
        "offering_deck": null,
        "offering_image_1": "https://img1.wsimg.com/isteam/stock/87385/:/rs=w:600,h:300,cg:true,m/cr=w:600,h:300",
        "offering_image_2": null,
        "offering_image_3": null,
        "offering_image_4": null,
        "offering_image_5": null,
        "sponsor_logo":null,
        "sponsor_contact_name":null,
        "sponsor_contact_title":null,
        "sponsor_contact_email":null,
        "sponsor_contact_phone":null,
        "sponsor_description":null,
        "sponsor_leadership_1_image":null,
        "sponsor_leadership_1_name":null,
        "sponsor_leadership_1_title":null,
        "sponsor_leadership_1_linkedin":null,
        "sponsor_leadership_2_image":null,
        "sponsor_leadership_2_name":null,
        "sponsor_leadership_2_title":null,
        "sponsor_leadership_2_linkedin":null,
        "sponsor_video":null,
        "profile_image":null
    },
    {
        "unique_id":4,
        "sponsor_name": "Sandstone Partners",
        "offering_name": "620 Hudson House LLC",
        "structure_name": "Qualified Opportunity Fund",
        "asset_class_id": 1,
        "offering_description": "We purchased a 15,000 SF historic property in the heart of Hudson NY, only 1 block from the main town square and we are expanding and redeveloping it into a professionally-managed independent boutique hotel with 55-rooms, a restaurant, bar, library, spa, and event space. We are shovel-ready and have all the entitlements in-place, and the CEO of the fund manager lives only three blocks away.",
        "offering_webpage": "https://sandstonere.com/",
        "sector_name": "Industrial",
        "strategy_name": "Ground Up Construction",
        "state_abbreviation":  "CA,NC,AZ",
        "portfolio_type_name": "Single Asset",
        "investor_requirement_name": "Accredited Only",
        "fundraising_status_name": "Open",
        "target_irr": null,
        "target_equity_multiple": null,
        "target_cash_on_cash": null,
        "minimum_investment": 500000,
        "estimated_hold_period": "10+ years",
        "estimated_first_distribution": null,
        "offering_webinar": "10+ years",
        "offering_deck": null,
        "offering_image_1": "https://img1.wsimg.com/isteam/stock/87385/:/rs=w:600,h:300,cg:true,m/cr=w:600,h:300",
        "offering_image_2": null,
        "offering_image_3": null,
        "offering_image_4": null,
        "offering_image_5": null,
        "sponsor_logo":null,
        "sponsor_contact_name":null,
        "sponsor_contact_title":null,
        "sponsor_contact_email":null,
        "sponsor_contact_phone":null,
        "sponsor_description":null,
        "sponsor_leadership_1_image":null,
        "sponsor_leadership_1_name":null,
        "sponsor_leadership_1_title":null,
        "sponsor_leadership_1_linkedin":null,
        "sponsor_leadership_2_image":null,
        "sponsor_leadership_2_name":null,
        "sponsor_leadership_2_title":null,
        "sponsor_leadership_2_linkedin":null,
        "sponsor_video":null,
        "profile_image":null
    },
    {
        "unique_id":5,
        "sponsor_name": "Ozone Capital",
        "offering_name": "828 Studios OZ Fund",
        "structure_name": "Qualified Opportunity Fund",
        "asset_class_id": 1,
        "offering_description": "This QOZ Fund will created a movie studio in addition to provide financing for firm projects. The movie studio will consist of 100,000 square feet of buildings that include sound stages, offices and post production facilities, amongst other venues. The facilities will cost $50 million to build and the additional $125 million will be used for project financing.",
        "offering_webpage": "https://www.ozonecapmarkets.com/courses-4/828-studios-oz-fund",
        "sector_name": "Mixed Use",
        "strategy_name": "Ground Up Construction",
        "state_abbreviation":  "CA,NC,AZ",
        "portfolio_type_name": "Single Asset",
        "investor_requirement_name": "Accredited Only",
        "fundraising_status_name": "Open",
        "target_irr": "16,9%",
        "target_equity_multiple": null,
        "target_cash_on_cash": null,
        "minimum_investment": 250000,
        "estimated_hold_period": "10+ years",
        "estimated_first_distribution": null,
        "offering_webinar": null,
        "offering_deck": null,
        "offering_image_1": "https://img1.wsimg.com/isteam/stock/87385/:/rs=w:600,h:300,cg:true,m/cr=w:600,h:300",
        "offering_image_2": null,
        "offering_image_3": null,
        "offering_image_4": null,
        "offering_image_5": null,
        "sponsor_logo":null,
        "sponsor_contact_name":null,
        "sponsor_contact_title":null,
        "sponsor_contact_email":null,
        "sponsor_contact_phone":null,
        "sponsor_description":null,
        "sponsor_leadership_1_image":null,
        "sponsor_leadership_1_name":null,
        "sponsor_leadership_1_title":null,
        "sponsor_leadership_1_linkedin":null,
        "sponsor_leadership_2_image":null,
        "sponsor_leadership_2_name":null,
        "sponsor_leadership_2_title":null,
        "sponsor_leadership_2_linkedin":null,
        "sponsor_video":null,
        "profile_image":null
    }
]
